spring.application.name=task-manager

spring.datasource.url=jdbc:h2:mem:taskdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

logging.level.com.example.taskmanager=INFO

stats.export.demo.key=sk_live_4f8a2c9d7b1e4a3f9c0d6e2b8a5f1234_123
